services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Moscow
